### ISSUE TITLE
Failed assertion in EnumHelpers.GetRawValue

### ISSUE THREAD

**Issue by SeeminglyScience** [SeeminglyScience/ClassExplorer#12]
```powershell
fit -f dispparams|Format-MemberSignature
Process terminated. Assertion failed.
   at ClassExplorer.Poly.Assert(Boolean condition) in C:\Users\patrick\Documents\Projects\ClassExplorer\src\ClassExplorer\Poly.cs:line 79
   at ClassExplorer.EnumHelpers.GetRawValue(Object value) in C:\Users\patrick\Documents\Projects\ClassExplorer\src\ClassExplorer\EnumHelpers.cs:line 43
   at ClassExplorer.SignatureWriter.AttributeArgument(Type type, Object value) in C:\Users\patrick\Documents\Projects\ClassExplorer\src\ClassExplorer\SignatureWriter.cs:line 497
   at ClassExplorer.SignatureWriter.AttributeArgument(TypedArgument argument) in C:\Users\patrick\Documents\Projects\ClassExplorer\src\ClassExplorer\SignatureWriter.cs:line 475
   at ClassExplorer.SignatureWriter.Attribute(Type type, TypedArgumentList arguments, Boolean isReturn) in C:\Users\patrick\Documents\Projects\ClassExplorer\src\ClassExplorer\SignatureWriter.cs:line 412
   at ClassExplorer.SignatureWriter.Attribute(Type type, TypedArgumentList arguments) in C:\Users\patrick\Documents\Projects\ClassExplorer\src\ClassExplorer\SignatureWriter.cs:line 390
   at ClassExplorer.SignatureWriter.Attribute(StructLayoutAttribute layout) in C:\Users\patrick\Documents\Projects\ClassExplorer\src\ClassExplorer\SignatureWriter.cs:line 455
   at ClassExplorer.SignatureWriter.Member(Type type) in C:\Users\patrick\Documents\Projects\ClassExplorer\src\ClassExplorer\SignatureWriter.cs:line 1158
   at ClassExplorer.Commands.FormatMemberSignatureCommand.ProcessRecord() in C:\Users\patrick\Documents\Projects\ClassExplorer\src\ClassExplorer\Commands\FormatMemberSignatureCommand.cs:line 93
```

**Comment by SeeminglyScience** [comment]
Fixed in #14
